# Generated by Django 5.0.7 on 2024-07-10 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='conversation',
            table='conversations',
        ),
    ]
